### ISSUE TITLE
Emulator crashing on launching the app

### ISSUE THREAD

**Issue by Agusioma** [android/health-samples#70] opened 2022-12-16 18:54 UTC
The app is working fine on my watch, but it stops once launched. Checking the logcat gives me this. Developer options are activated in the emulator.

```kotlin
--------- beginning of crash
2022-12-16 21:48:06.472  6992-6992  AndroidRuntime          com.terrencealuda.tcardio            E  FATAL EXCEPTION: main
                                                                                                    Process: com.terrencealuda.tcardio, PID: 6992
                                                                                                    java.lang.Exception: Not yet implemented
                                                                                                    	at androidx.health.services.client.impl.internal.StatusCallback.onFailure(StatusCallback.kt:42)
                                                                                                    	at androidx.health.services.client.impl.internal.IStatusCallback$Stub.onTransact(IStatusCallback.java:80)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1159)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1123)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bca20c9, Dispatche
``` 

@breanatate, could you assist?

**Comment by Agusioma** [comment] 2022-12-21 06:11
No. Just the default one

**Comment by ithinkihaveacat** [comment] 2023-01-09 11:15
@Agusioma Can you clarify which specific sample? There's multiple applications in this repository ([HealthConnectSample](https://github.com/android/health-samples/tree/main/health-connect/HealthConnectSample), [MeasureDataSample](https://github.com/android/health-samples/tree/main/health-services/MeasureData), etc.).

Also your log fragment shows a non-sample package name (`com.terrencealuda.tcardio`).

**Comment by zelotbe** [comment] 2023-01-11 21:13
Hi, Were you able to fix the issue?
I'm currently having the exact same error when running the PassiveDataCompose sample:

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.passivedatacompose, PID: 30333
>     java.lang.Exception: Not yet implemented
>         at androidx.health.services.client.impl.internal.StatusCallback.onFailure(StatusCallback.kt:42)
>         at androidx.health.services.client.impl.internal.IStatusCallback$Stub.onTransact(IStatusCallback.java:80)
>         at android.os.Binder.execTransactInternal(Binder.java:1159)
>         at android.os.Binder.execTransact(Binder.java:1123)
>     	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@806352d, Dispatchers.Main.immediate]
>

**Comment by Agusioma** [comment] 2023-01-11 21:16
Not yet @breanatate  😃. And yes, it's the same sample- PassiveDataSample. I closed the issue assuming that I had misconfigured something somewhere in my environment.

**Comment by Agusioma** [comment] 2023-01-11 21:18
> @Agusioma Can you clarify which specific sample? There's multiple applications in this repository ([HealthConnectSample](https://github.com/android/health-samples/tree/main/health-connect/HealthConnectSample), [MeasureDataSample](https://github.com/android/health-samples/tree/main/health-services/MeasureData), etc.).
> 
> Also your log fragment shows a non-sample package name (`com.terrencealuda.tcardio`).

PassiveDataSample. Yes, the package name is different because I tried renaming it.

**Comment by zelotbe** [comment] 2023-01-11 21:31
> Not yet @zelotbe 😃. And yes, it's the same sample- PassiveDataSample. I closed the issue assuming that I had misconfigured something somewhere in my environment.

Oh alright, Thanks for the info 😉

**Comment by garanj** [comment] 2023-01-11 21:33
Can you confirm the version of Health Services installed?

`adb shell dumpsys package com.google.android.wearable.healthservices | grep versionCode`

Thanks

**Comment by garanj** [comment] 2023-01-11 21:37
@zelotbe Are you able to confirm whether you're also having this issue on the emulator only? Or also on a physical device?

**Comment by zelotbe** [comment] 2023-01-11 21:48
> @zelotbe Are you able to confirm whether you're also having this issue on the emulator only? Or also on a physical device?

Hi, thank you for your response.
I'm currently running this on the emulator.
My healthservices versionCode is 27327, minSdk = 30 targetSdk = 30.

I'll try the sample on a physical device.

**Comment by garanj** [comment] 2023-01-11 21:56
I can't reproduce this on the emulator, but the versionCode on my emulator is `versionCode=70695`.

I am going to see if I can get hold of the version you have. If you're able to get hold of a more recent emulator image, it may contain a later version such as 70695, if you're able to try that?

**Comment by garanj** [comment] 2023-01-22 09:39
Having added this documentation, I'm going to close this issue for now. We've an internal issue to track making improvements to emulator updates to tackle this, but hopefully with the documentation this is enough to help unblock developers for now.

If you feel this is inadequate, please reopen.

**Closed by garanj** 2023-01-22 09:39 UTC
