### ISSUE TITLE
Measure Data sample app only recognizes Heart Rate capability

### ISSUE THREAD

**Issue by bensadiku** [android/health-samples#47] opened 2022-09-18 18:51 UTC
Hello, I'm using the Measure Data sample app, with the latest dependency:
`implementation "androidx.health:health-services-client:1.0.0-alpha03"`

The issue I'm finding is that the `MeasureClient` capabilities returns only heart rate, while the device I'm using (Galaxy Watch 5/5pro) has way more sensors that can be used. 

What am i missing ?

**Comment by bensadiku** [comment] 2022-09-18 19:16
Looks like there's quite more work done on AOSP on this area, is there a release coming soon?

**Comment by Agusioma** [comment] 2022-12-11 16:24
Same issue over here. Keeps crashing on adding other data types.

**Comment by breanatate** [comment] 2022-12-12 18:03
Hi there, yes only HR is supported for MeasureClient at the moment. Please make sure to check capabilities before substituting other data types, that way it won't crash. 

What's your use case? Which data types are you trying to add in?

**Comment by Agusioma** [comment] 2022-12-12 18:12
> Hi there, yes only HR is supported for MeasureClient at the moment. Please make sure to check capabilities before substituting other data types, that way it won't crash.
> 
> What's your use case? Which data types are you trying to add in?

Hello @breanatate . Actually, I am using the PassiveMonitoringClient. I was just adding emphasis on the question raised by @bensadiku. So even if it's MeasureCLient,why should it be Heart Rate only? Or should we access the sensors from scratch ourselves? Because I see other apps recording other DataTypes. Or is there something else we are supposed to do?  tried adding others such as Calories.

**Comment by Agusioma** [comment] 2022-12-12 18:17
> Hi there, yes only HR is supported for MeasureClient at the moment. Please make sure to check capabilities before substituting other data types, that way it won't crash.
> 
> What's your use case? Which data types are you trying to add in?

Hello @breanatate. What about PassiveMonitoringClient? Because that's what I am using and it's the same issue.

**Comment by breanatate** [comment] 2022-12-12 18:22
PassiveMonitoringClient supports more data types than MeasureClient, and we've outlined the expected behaviors [here](https://developer.android.com/training/wearables/health-services/compatibility#passive_monitoring_client). 

 If you check the device capabilities ([process here](https://developer.android.com/training/wearables/health-services/passive#check-capabilities)) before starting PassiveMonitoringClient, you should be able to anticipate if the app will crash/support the data types.

**Comment by Agusioma** [comment] 2022-12-12 18:29
Aah perfect. I have always skipped this page(https://developer.android.com/training/wearables/health-services/compatibility#passive_monitoring_client). So I was trying to invoke VO2_MAX in PassiveMonitoringClient and that's why it was crashing. Let me check it out. I will ping you in case of anything @breanatate.

**Comment by breanatate** [comment] 2022-12-12 18:51
VO2_MAX can only be measured during active exercise (if the device has the appropriate capabilities).

**Comment by bensadiku** [comment] 2022-12-12 21:38
@breanatate I'm using the latest Samsung Galaxy Watch (watch5 & watch 5pro) and i still don't see any sensor other than Heart Rate. Any hint?

**Comment by breanatate** [comment] 2022-12-12 22:04
@bensadiku At the moment, MeasureClient only supports heart rate. If there are other data types you're interested in, they may be supported in PassiveMonitoringClient or ExerciseClient.

**Comment by bensadiku** [comment] 2022-12-14 08:08
> @bensadiku At the moment, MeasureClient only supports heart rate. If there are other data types you're interested in, they may be supported in PassiveMonitoringClient or ExerciseClient.

I was interested in spo2. That doesn't seem the available in any of the clients but the watch supports it.

**Comment by Agusioma** [comment] 2022-12-14 09:57
> > @bensadiku At the moment, MeasureClient only supports heart rate. If there are other data types you're interested in, they may be supported in PassiveMonitoringClient or ExerciseClient.
> 
> I was interested in spo2. That doesn't seem to be available in any of the clients but the watch supports it.

@bensadiku maybe you will need to check out the [Health Connect API](https://developer.android.com/jetpack/androidx/releases/health-connect). Maybe if @breanatate has another walkaround to that.

**Comment by garanj** [comment] 2023-01-22 09:47
Closing this out as working as intended for `MeasureClient` at this time.

**Closed by garanj** 2023-01-22 09:47 UTC
