### ISSUE TITLE
Connection to service is not available for package 'com.google.android.wearable.healthservices' and action 'com.google.android.wearable.healthservices.ExerciseClient'.

### ISSUE THREAD

**Issue by sadaks-me** [android/health-samples#4] opened 2021-07-09 21:48 UTC
E/ServiceConnection: Connection to service is not available for package 'com.google.android.wearable.healthservices' and action 'com.google.android.wearable.healthservices.ExerciseClient'.
E/ServiceConnection: Connection disconnected and maximum number of retries reached.
    java.util.concurrent.CancellationException: Service not available
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.connect(ServiceConnection.java:145)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.enqueue(ServiceConnection.java:203)
        at androidx.health.services.client.impl.ipc.internal.ConnectionManager.handleMessage(ConnectionManager.java:123)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:220)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by haozes** [comment] 2021-08-17 08:16
same issue on Galaxy Watch 4 wearos3

**Comment by RKDeveloper12** [comment] 2021-08-31 16:40
Experiencing the same issue.

**Comment by littleariel** [comment] 2021-08-31 22:50
Same issue here.

**Comment by a-v-ebrahimi** [comment] 2021-09-08 07:32
I have same issue on Galaxy Watch 4, WearOS.

**Comment by nkumar-ust** [comment] 2021-09-16 05:18
I am also facing same issue on Samsung Wear watch 4 classic. Is Health Service APIs are not yet available on Samsung Watch 4/classic?

**Comment by garanj** [comment] 2021-10-12 09:51
We've recently updated the samples for the `alpha02` release - there have been [quite a few changes](https://developer.android.com/jetpack/androidx/releases/health#health-services-client-1.0.0-alpha02) to the Health Services APIs since the Alpha01 release.

Are you able to try the updated sample?

**Comment by garanj** [comment] 2021-11-03 22:49
Going to close this one out for now - if the issue remains with `alpha02`, can reopen.

**Closed by garanj** 2021-11-03 22:49 UTC

**Comment by bensadiku** [comment] 2022-10-03 12:28
@garanj I'm able to reproduce same issue even after alpha03. Is there a new release coming? It's been nearly a year since the last release...

**Comment by miloti-aliu** [comment] 2022-10-13 13:06
@garanj same issue for me even on alpha03.

**Comment by artillerymans** [comment] 2023-02-19 04:08
@miloti-aliu  same issue for me even on alpha10

**Comment by miloti-aliu** [comment] 2023-02-19 15:49
@artillerymans this has been fixed on beta version. Currently I am using beta01 version and it works fine.

**Comment by artillerymans** [comment] 2023-02-20 02:44
![image](https://user-images.githubusercontent.com/16060581/219997613-2fc03848-f803-4fd9-88d9-199df2cc5850.png)
Where is beta01? Has it been released?

**Comment by miloti-aliu** [comment] 2023-02-21 08:57
Yes, you can find it here: https://developer.android.com/jetpack/androidx/releases/health

**Comment by breanatate** [comment] 2023-02-21 15:17
@artillerymans the original issue was regarding the Health Services API (currently on beta02).

Are you seeing a similar error message on Health Connect (on alpha10)? Can you share the output?
