### ISSUE TITLE
App crash when onClick session item

### ISSUE THREAD

**Issue by ThantSin17** [android/health-samples#25] opened 2022-06-03 04:58 UTC
java.lang.NoSuchMethodError: No virtual method toHoursPart()I in class Ljava/time/Duration; or its super classes (declaration of 'java.time.Duration' appears in /apex/com.android.art/javalib/core-oj.jar)
        at com.example.healthconnectsample.data.HealthConnectUtilKt.formatTime(HealthConnectUtil.kt:41)
        at com.example.healthconnectsample.presentation.screen.activitysessiondetail

**Comment by garanj** [comment] 2022-06-08 10:19
Hi @ThantSin17 Thanks for the feedback - are you able to try the updated sample to see if the issue is resolved for you?

**Comment by garanj** [comment] 2022-06-15 11:49
Closing this issue, please reopen if it isn't fixed for you.

**Closed by garanj** 2022-06-15 11:49 UTC
